### ISSUE TITLE
ERROR: Unable to find Promise impementation

### ISSUE THREAD

**Issue by cboettig** [ropensci/jsonld#2]
```r
library(httr)
library(jsonld)
library(jsonlite)

rawdoc <- GET("https://raw.githubusercontent.com/codemeta/codemeta/master/examples/example-codemeta-rdataone.json")
doc <- content(rawdoc)


## ERROR
expand(doc)

## ERROR
to_rdf(doc)

## extract context
context_addr <- content(rawdoc, "parsed", "application/json")["@context"]
context <- content(GET(as.character(context)))

## ERROR
compact(doc, context)
```

@jeroenooms I guess this is do to the promise stuff you mentioned not being available in V8?  (Or maybe I'm just not making the function call correctly?)  Do you see anyway around this?  It's not obvious to me what in in particular in this example differs from the sample example and is causing the Promise calls...

**Comment by cboettig** [comment]
@jeroenooms I'm wondering if this is an issue we could work around just by retrieving the context JSON manually?  If so, maybe a higher-level wrapper could work around this?

For instance, if I just strip off the context and provide it separately, `compact` works as expected:


```r
library(magrittr)
library(httr)
library(jsonld)
library(jsonlite)

rawdoc <- GET("https://raw.githubusercontent.com/codemeta/codemeta/master/examples/example-codemeta-rdataone.json")
txt_doc <- content(rawdoc)
json_doc <- content(rawdoc, "parsed", "application/json")

## Stip out context
context <- json_doc["@context"] %>% as.character() %>% GET() %>% content()

## doc without context
doc <- toJSON(json_doc[-1])

## YAY
compact(doc, context)
```

But I cannot get `expand` or `to_rdf` to work this way. With no context, expand is empty:

```r
## Where'd the rest of it go? Do we need to add the context back?
expand(doc)
```

So I tried to append the context JSON directly:

```r
full_doc <- fromJSON(context) %>% c(json_doc[-1]) %>% toJSON()
## ERROR
expand(full_doc)
```

and I get a new ERROR that full_doc isn't jsonld any more.  Maybe something along these lines could work though?
but

**Comment by jeroen** [comment]
@cboettig @sckott I have implemented a custom document retriever which calls back to from JavaScript to R to perform the downloads. Can you try again?

**Comment by sckott** [comment]
just tried with new version, works for me

**Comment by jeroen** [comment]
@sckott cool! So everything works now?

**Comment by cboettig** [comment]
Nice, works like charm! :rocket:
