### ISSUE TITLE
Functions should support local paths and/or json objects

### ISSUE THREAD

**Issue by cboettig** [ropensci/jsonld#4]
Currently, all functions take either a URL or a JSON string.  This makes the workflow for the presumably common case of a local json document somewhat cumbersome, e.g.

```r
# install_github("codemeta/codemetar")
ex <- system.file("examples/full-codemeta.json", package = "codemetar")

doc <- paste(readLines(ex), collapse = "\n")
jsonld_flatten(doc)
```

Instead of merely:

```r
jsonld_flatten(ex)
```

Do you think we could add the additional logic so that the functions can identify when the argument corresponds to existing file, just as it currently decides if the argument is a URL or raw json?

Might also be good to consider if the functions should operate on an object returned by `read_json`, but since that's just a list rather than some S3 class probably that doesn't make as much sense.  

Thanks, the package has been awesome btw.  Just starting to appreciate the use of `jsonld_frame`, which is a really clever way to turn data into a predictable format (e.g. often you can represent the exact same data (graph) in different ways in json, so it's neat to have a mechanism that can take any equivalent representation and format it in a predictable tree structure for easy programmatic use.)

**Comment by jeroen** [comment]
Thanks, @cboettig. I've added this in https://github.com/ropensci/jsonld/commit/6d3cb9ff96be98af783edf4288b0a89187539567. Looking forward to reading about your use cases.

**Comment by cboettig** [comment]
@jeroen very nice, thanks!  Here's my current draft which explores the motivation for some of these functions, framing in particular: https://codemeta.github.io/codemetar/articles/JSON-LD-framing.html  Now that I'm wrapping my head around how framing works I can probably revise that to write a more compelling use case, but the basic idea is that you can provide a skeleton frame (kinda like a schema) saying "this is how I want my data formatted for my application".  I think framing is pretty cool!
