### ISSUE TITLE
Create context from list

### ISSUE THREAD

**Issue by grosscol** [ropensci/jsonld#7]
This is a feature request to add a function that builds the context section of a json-ld document from a list.

I have a use case where I'm doing some data analysis and using linked data as the output.  This works out will with generating a data table and using `jsonlite::toJSON` for a list that ends up in a json-ld document.  The pain point I currently have is building a context for the json-ld document.

A context section is just a list of aliases.
```R
context <- list(
            "performer"    = "http://ns.example.com/ontology#NOID_0000001",
            "has_part"     = "http://ns.example.com/ontology#NOID_0000002",
            "has_mastery"  = "http://ns.example.com/ontology#NOID_00000011",
            "has_downward" = "http://ns.example.com/ontology#NOID_00000023" )
```

However, toJSON is unable to convert this to the correct structure, because it will wrap each value in an array.  For the scope of jsonlite, that is the desired behavior.
```json
{
    "performer": ["http://ns.example.com/ontology#NOID_0000001"],
    "has_part": ["http://ns.example.com/ontology#NOID_0000002"],
    "has_mastery": ["http://ns.example.com/ontology#NOID_00000011"],
    "has_downward": ["http://ns.example.com/ontology#NOID_00000023"]
}
```
To avoid the array wrapped values above, my current approach is similar to:
```R
format_key_value <- function(k, v){ paste(k,":",v) }
context_from_list <- function(x){ mapply(format_key_value, names(x), x)}
```

**Comment by jeroen** [comment]
I'm not sure how this gets called but you could try `toJSON(x, auto_unbox = TRUE)` ?

**Comment by cboettig** [comment]
@grosscol FWIW, the approach @jeroen mentions is also precisely what we're use to create a context from a `list` (or input `csv` file) here: https://github.com/ropensci/codemetar/blob/master/R/crosswalk.R#L34

**Comment by grosscol** [comment]
Thank you, @jeroen & @cboettig.  I missed the meaning of unbox in the documentation for `toJSON`.  I think it's not a bridge too far to use toJSON with unboxing to build json-ld documents.
