### ISSUE TITLE
Some triples not found or emitted from JSON-LD using @vocab

### ISSUE THREAD

**Issue by gaurav** [ropensci/jsonld#9]
I've noticed that for one of my JSON-LD files, jsonld_1.2 does not emit all the triples I'd expect from the [jsonld_to_rdf](https://github.com/ropensci/jsonld/blob/6d3cb9ff96be98af783edf4288b0a89187539567/R/wrappers.R#L86) function. I tried to simplify the file as much as possible, and ended up with the [attached file](https://github.com/ropensci/jsonld/files/1557348/triples_missing.json.txt). In response, jsonld emits the following triples:

```
_:b2 <http://www.nexml.org/2009/state> "Dcs347685" .
_:b3 <http://www.nexml.org/2009/state> "Dcs347688" .
_:b4 <http://www.nexml.org/2009/state> "Dcs347687" .
_:b5 <http://www.nexml.org/2009/state> "Dcs347686" .
_:b6 <http://www.nexml.org/2009/state> "uncertain_state_set726720" .
_:b7 <http://www.nexml.org/2009/state> "Dcs347689" .
```

This may be because my JSON-LD file is malformed in some way, but I'm struggling to see why it picked up those particular triples. Why not also include the information from "characters"? Where are the triples about the top-level entity or "nexml"? Is this related to our use of "@vocab"? Any help in understanding what's going on here would be hugely appreciated!

**Comment by cboettig** [comment]
@gaurav Have you compared against https://json-ld.org/playground/ output for RDF?  Does it also miss triples?

**Comment by cboettig** [comment]
@gaurav you might also test by first adding an `"@base": "http://example.com/"` or some such to the `@context` object?

Not sure how the json-ld R library handles a default `@base` when it encounters bare ids.  playground puts it own URL in that place, e.g. [playground ex](http://tinyurl.com/y9o6u4uw
).  What does python rdflib do?

**Comment by gaurav** [comment]
Yes, that worked! The JSON-LD Playground does not miss any triples as far as I can tell: http://tinyurl.com/y9o6u4uw, but `@base` fixes it for jsonld_1.2. It now gives me [all the triples](https://github.com/ropensci/jsonld/files/1557390/triples.txt), which looks to be exactly identical to playground, which appears to add an implicit `@base` of "https://json-ld.org/playground/". In Python, rdfpipe ([rdflib](https://rdflib.readthedocs.io/en/stable/)) seems to implicit use a `@base` of the current directory (e.g. `file:///C:/Users/Username/code/nexld/tests/example_jsonld`).

I'm going to leave this issue open to ask whether jsonld_1.2 should have a default `@base` as well, but my immediate issue has been sorted out. Thanks!

**Comment by cboettig** [comment]
so it looks like one should just be setting `options = list(base=<baseURI>)` in the call to `jsonld_to_rdf` if the JSON-LD context does not itself set a `@base`.  

https://github.com/ropensci/jsonld/blob/9a5dcb1b1e04aee218dc1dead06fa0bcc489ee1e/inst/js/jsonld.js#L889-L896
